% -------------------------------------------------------------------
%  Generated by MATLAB on 24-Mar-2015 18:17:58
%  MATLAB version: 8.3.0.532 (R2014a)
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

I = saveVarsMat.I; % <1x1500 double> too many elements

clear saveVarsMat;
